apiVersion: v1
kind: Service
metadata:
  name: {{ include "apisix.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $value := .Values.gateway.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    {{- include "apisix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gateway.type }}
  {{- if eq .Values.gateway.type "LoadBalancer" }}
  {{- if .Values.gateway.loadBalancerIP }}
  loadBalancerIP: {{ .Values.gateway.loadBalancerIP }}
  {{- end }}
  {{- if .Values.gateway.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.gateway.loadBalancerSourceRanges }}
  - {{ $cidr }}
  {{- end }}
  {{- end }}
  {{- end }}
  externalIPs:
  {{- range $ip := .Values.gateway.externalIPs }}
  - {{ $ip }}
  {{- end }}
  ports:
  {{- if .Values.gateway.http.enabled }}
  - name: apisix-gateway
    port: {{ .Values.gateway.http.servicePort }}
    targetPort: {{ .Values.gateway.http.containerPort }}
  {{- if (and (eq .Values.gateway.type "NodePort") (not (empty .Values.gateway.http.nodePort))) }}
    nodePort: {{ .Values.gateway.http.nodePort }}
  {{- end }}
    protocol: TCP
  {{- end }}
  {{- if or .Values.gateway.tls.enabled }}
  - name: apisix-gateway-tls
    port: {{ .Values.gateway.tls.servicePort }}
    targetPort: {{ .Values.gateway.tls.containerPort }}
  {{- if (and (eq .Values.gateway.type "NodePort") (not (empty .Values.gateway.tls.nodePort))) }}
    nodePort: {{ .Values.gateway.tls.nodePort }}
  {{- end }}
    protocol: TCP
  {{- end }}
  selector:
    {{- include "apisix.selectorLabels" . | nindent 4 }}
